// Public repository metadata verified on 2026-10-08.
// Refresh from GitHub + Cloudflare audit; no credentials or private repository contents.
import type { TranslatedProjectItem } from './project_translations';
import { recentGithubProjects } from './recent_projects';

export type GithubProject = TranslatedProjectItem & { titleFa: string; descriptionFa: string; featuresFa?: string[] };
export const githubCatalogVerifiedAt = "2026-10-08T11:56:24.345Z";
export const githubProjects: GithubProject[] = [
  ...recentGithubProjects,
  {
    "id": "github-pimx-agent",
    "repoName": "PIMX_AGENT",
    "title": "AI research and creation workspace",
    "titleEn": "AI research and creation workspace",
    "titleFa": "فضای کار هوش مصنوعی",
    "description": "A Next.js AI workspace with provider configuration, conversations, attachments, project/library organization, research tools and document/presentation workflows.",
    "descriptionFa": "فضای کار Next.js با ارائه‌دهندگان مختلف هوش مصنوعی، گفتگو، فایل‌های پیوست، کتابخانه و پروژه‌ها؛ ابزارهایی برای پژوهش و ساخت سند و ارائه.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_AGENT",
    "accent": "emerald",
    "category": "ai",
    "badge": "AI WORKSPACE",
    "language": "TypeScript",
    "technologies": [
      "Next.js",
      "AI APIs",
      "React",
      "Three.js"
    ],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "nextjs",
      "persian",
      "pimx",
      "react",
      "threejs",
      "typescript"
    ],
    "updatedAt": "2026-10-07T16:30:24Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxagent.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:20.272Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_AGENT/blob/main/README.md",
    "features": [
      "Conversations, attachments and provider configuration",
      "Project libraries and research workflows",
      "Document and presentation workflows"
    ],
    "featuresFa": [
      "گفتگو، فایل پیوست و تنظیم ارائه‌دهندگان",
      "کتابخانهٔ پروژه‌ها و جریان‌های پژوهش",
      "جریان‌های ساخت سند و ارائه"
    ],
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "github-pimx-morph",
    "repoName": "PIMX_MORPH",
    "title": "File conversion workbench",
    "titleEn": "File conversion workbench",
    "titleFa": "تبدیل فایل در مرورگر",
    "description": "A browser conversion workbench for images, PDFs, documents, audio and structured data. Separate converter functions handle each supported transformation.",
    "descriptionFa": "مجموعه‌ابزار تبدیل فایل در مرورگر برای تصویر، PDF، سند، صوت و داده‌های ساختاریافته؛ با پردازش سمت کاربر برای فرمت‌های پشتیبانی‌شده.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_MORPH",
    "accent": "rose",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "React",
      "PDF",
      "Web Audio",
      "Express",
      "Vite"
    ],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "express",
      "persian",
      "pimx",
      "react",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:29:44Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxmorph.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:21.358Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_MORPH/blob/main/README.md",
    "features": [
      "Separate converters for supported image and document formats",
      "Audio and structured-data conversion tools",
      "Browser-based workbench for choosing inputs and outputs"
    ],
    "featuresFa": [
      "مبدل‌های مجزا برای فرمت‌های تصویر و سند پشتیبانی‌شده",
      "ابزارهای تبدیل صوت و دادهٔ ساختاریافته",
      "فضای کار مرورگر برای انتخاب ورودی و خروجی"
    ],
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "pimx-veil",
    "repoName": "PIMX_VEIL",
    "title": "Encrypted payload packaging",
    "titleEn": "Encrypted payload packaging",
    "titleFa": "بسته‌بندی و رمزنگاری فایل",
    "description": "A browser workbench that encrypts a payload and appends it, together with metadata, to a carrier file. Extraction recovers the encrypted envelope for password-based decryption.",
    "descriptionFa": "ابزار رمزنگاری و بسته‌بندی داده در کنار فایل میزبان، با فراداده برای استخراج مجدد و رمزگشایی با گذرواژه.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_VEIL",
    "accent": "cyan",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "Web Crypto",
      "React",
      "Vite",
      "Express"
    ],
    "topics": [
      "bilingual",
      "english",
      "express",
      "networking",
      "persian",
      "pimx",
      "privacy",
      "react",
      "typescript",
      "vite"
    ],
    "updatedAt": "2026-10-07T16:27:55Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxveil.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:22.334Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_VEIL/blob/main/README.md",
    "features": [
      "Encrypted payload packaged alongside a carrier file",
      "Envelope metadata for subsequent extraction",
      "Password-based encryption and decryption workflow"
    ],
    "featuresFa": [
      "بسته‌بندی دادهٔ رمزنگاری‌شده در کنار فایل میزبان",
      "فرادادهٔ بسته برای استخراج بعدی",
      "جریان رمزنگاری و رمزگشایی با گذرواژه"
    ],
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "pimx-node",
    "repoName": "PIMX_NODE",
    "title": "Peer-to-peer file transfer",
    "titleEn": "Peer-to-peer file transfer",
    "titleFa": "انتقال مستقیم فایل",
    "description": "A browser file-transfer workspace built around WebRTC data channels, a Node.js WebSocket signaling service and AES-GCM encryption of transferred chunks.",
    "descriptionFa": "ابزار انتقال فایل با WebRTC و سرور سیگنالینگ WebSocket در Node.js؛ تقسیم فایل به قطعه‌ها و رمزنگاری AES-GCM در مسیر انتقال.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_NODE",
    "accent": "indigo",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "React",
      "WebRTC",
      "WebSocket",
      "AES-GCM",
      "Express",
      "Vite"
    ],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "express",
      "persian",
      "pimx",
      "react",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:27:43Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxnode.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:21.206Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_NODE/blob/main/README.md",
    "features": [
      "WebRTC peer connections with WebSocket signaling",
      "Chunked file transfer with AES-GCM encryption",
      "Browser interface backed by Node.js services"
    ],
    "featuresFa": [
      "اتصال همتا با WebRTC و سیگنالینگ WebSocket",
      "انتقال قطعه‌ای فایل با رمزنگاری AES-GCM",
      "رابط مرورگر در کنار سرویس‌های Node.js"
    ],
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "pimx-moji",
    "repoName": "PIMX_MOJI",
    "title": "Image-to-character creative studio",
    "titleEn": "Image-to-character creative studio",
    "titleFa": "استودیوی هنر متنی",
    "description": "A browser image-to-character art studio with preset styles, a character picker, canvas processing, previews and conversion history.",
    "descriptionFa": "استودیوی تبدیل تصویر به کاراکتر با سبک‌های مختلف، انتخاب نمادها، بوم، پیش‌نمایش و تاریخچهٔ خروجی‌ها.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_MOJI",
    "accent": "cyan",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "Express",
      "React",
      "Vite"
    ],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "express",
      "persian",
      "pimx",
      "react",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:27:50Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxmoji.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:22.352Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_MOJI/blob/main/README.md",
    "features": [
      "Image-to-character conversion with selectable styles",
      "Canvas preview and character picker",
      "Output history and creative text layouts"
    ],
    "featuresFa": [
      "تبدیل تصویر به کاراکتر با سبک‌های قابل انتخاب",
      "پیش‌نمایش بوم و انتخاب کاراکتر",
      "تاریخچهٔ خروجی‌ها و چیدمان‌های هنر متنی"
    ],
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "github-pimxsats",
    "repoName": "PIMXSATS",
    "title": "Satellite orbit explorer",
    "titleEn": "Satellite orbit explorer",
    "titleFa": "رصد ماهواره‌ها روی کرهٔ سه‌بعدی",
    "description": "An interactive satellite and solar-system explorer. A Three.js globe, satellite.js orbit propagation and pass predictions turn orbital data into a visual workspace.",
    "descriptionFa": "نمایش کرهٔ زمین با Three.js، محاسبهٔ مدار و پیش‌بینی گذر ماهواره با satellite.js و تجربهٔ تعاملی منظومهٔ شمسی.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMXSATS",
    "accent": "emerald",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "React",
      "Three.js",
      "satellite.js",
      "React Three Fiber",
      "Next.js"
    ],
    "topics": [
      "astronomy",
      "bilingual",
      "english",
      "nextjs",
      "orbital-mechanics",
      "persian",
      "pimx",
      "react",
      "satellite-tracking",
      "threejs",
      "typescript",
      "visualization"
    ],
    "updatedAt": "2026-10-07T16:27:02Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxsats.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:19.327Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMXSATS/blob/main/README.md",
    "features": [
      "Interactive Earth and solar-system scenes with Three.js",
      "Satellite orbital calculations with satellite.js",
      "Pass predictions and geographic visualization"
    ],
    "featuresFa": [
      "صحنه‌های تعاملی زمین و منظومهٔ شمسی با Three.js",
      "محاسبات مدار ماهواره با satellite.js",
      "پیش‌بینی گذر و نمایش جغرافیایی"
    ],
    "linkKind": "website",
    "activitySource": "http",
    "previewImage": "/project-previews/github-pimxsats.jpg?v=owner-20261008"
  },
  {
    "id": "github-pimx-swap",
    "repoName": "PIMX_SWAP",
    "title": "Keyboard layout correction for Windows",
    "titleEn": "Keyboard layout correction for Windows",
    "titleFa": "اصلاح چیدمان صفحه‌کلید",
    "description": "A local Windows keyboard-layout correction utility built with Rust, Tauri 2, React and TypeScript. It reconstructs physical key input and maps it to another layout: `sghl` → `سلام`.",
    "descriptionFa": "ابزار دسکتاپ ویندوز با Rust، Tauri 2 و React برای اصلاح متن تایپ‌شده با زبان اشتباه؛ نگاشت کلیدهای فیزیکی مثلاً sghl را به سلام تبدیل می‌کند.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_SWAP",
    "accent": "violet",
    "category": "featured",
    "badge": "DESKTOP APP",
    "language": "Rust",
    "technologies": [
      "Rust",
      "Tauri 2",
      "React"
    ],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "keyboard-layout",
      "persian",
      "pimx",
      "react",
      "rust",
      "tauri",
      "typescript",
      "vite",
      "web-app",
      "windows"
    ],
    "updatedAt": "2026-10-07T20:27:44Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_SWAP/blob/main/README.md",
    "features": [
      "Windows desktop application built with Rust and Tauri 2",
      "Physical-key mapping between keyboard layouts",
      "React and TypeScript interface"
    ],
    "featuresFa": [
      "اپ دسکتاپ ویندوز با Rust و Tauri 2",
      "نگاشت کلیدهای فیزیکی میان چیدمان‌های صفحه‌کلید",
      "رابط کاربری React و TypeScript"
    ],
    "previewImage": "/project-previews/github-pimx-swap.jpg?v=owner-20261008"
  },
  {
    "id": "github-pimxdash",
    "repoName": "PIMXDASH",
    "title": "A more useful Chrome new tab",
    "titleEn": "A more useful Chrome new tab",
    "titleFa": "داشبورد تب جدید مرورگر",
    "description": "A Manifest V3 Chrome/Chromium new-tab extension centered on bookmarks, fast search, focus tools and modular productivity widgets.",
    "descriptionFa": "افزونهٔ Chrome بر پایهٔ Manifest V3 برای تب جدید، بوکمارک‌ها، جست‌وجو، تمرکز و ابزارهای بهره‌وری.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMXDASH",
    "accent": "teal",
    "category": "featured",
    "badge": "BROWSER EXTENSION",
    "language": "TypeScript",
    "technologies": [
      "Chrome MV3",
      "React"
    ],
    "topics": [
      "bilingual",
      "bookmarks",
      "chrome-extension",
      "developer-tools",
      "english",
      "manifest-v3",
      "persian",
      "pimx",
      "productivity",
      "python",
      "react",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:29:48Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMXDASH/blob/main/README.md",
    "features": [
      "Chrome extension using Manifest V3",
      "New-tab bookmarks and search",
      "Focus and productivity tools"
    ],
    "featuresFa": [
      "افزونهٔ Chrome با Manifest V3",
      "بوکمارک و جست‌وجو در تب جدید",
      "ابزارهای تمرکز و بهره‌وری"
    ]
  },
  {
    "id": "pimx-wide",
    "repoName": "PIMX_WIDE",
    "title": "Browser encryption for text and files",
    "titleEn": "Browser encryption for text and files",
    "titleFa": "ابزار رمزنگاری در مرورگر",
    "description": "A multilingual text/file encryption interface using browser Web Crypto, AES-256-GCM and password-derived keys, with local records and optional visitor telemetry.",
    "descriptionFa": "رمزنگاری متن و فایل با Web Crypto، AES-256-GCM و کلید مشتق‌شده از گذرواژه؛ رابط چندزبانه با سوابق محلی و تله‌متری اختیاری.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_WIDE",
    "accent": "indigo",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "Web Crypto",
      "AES-GCM",
      "React"
    ],
    "topics": [
      "bilingual",
      "english",
      "networking",
      "persian",
      "pimx",
      "privacy",
      "react",
      "typescript",
      "vite"
    ],
    "updatedAt": "2026-10-07T16:28:00Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxwide.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:22.510Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_WIDE/blob/main/README.md",
    "features": [
      "AES-256-GCM through the browser Web Crypto API",
      "Password-derived keys for text and file workflows",
      "Multilingual interface with local records"
    ],
    "featuresFa": [
      "AES-256-GCM با Web Crypto در مرورگر",
      "کلید مشتق‌شده از گذرواژه برای متن و فایل",
      "رابط چندزبانه با سوابق محلی"
    ],
    "linkKind": "website",
    "activitySource": "http",
    "previewImage": "/project-previews/pimx-wide.jpg?v=owner-20261008"
  },
  {
    "id": "github-pimx-eltex",
    "repoName": "PIMX_ELTEX",
    "title": "AI content, prompts and project library",
    "titleEn": "AI content, prompts and project library",
    "titleFa": "کتابخانهٔ محتوای هوش مصنوعی",
    "description": "A Next.js publishing platform for AI-building episodes, code resources and project previews, with member accounts, comments and an administrative console.",
    "descriptionFa": "سایت Next.js برای ویدیوها، پرامپت‌ها، نمونه‌کد و پیش‌نمایش پروژه‌ها، با حساب کاربری، دیدگاه‌ها و مدیریت محتوا.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_ELTEX",
    "accent": "gold",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "JavaScript",
    "technologies": [
      "Next.js",
      "Framer Motion",
      "React"
    ],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "nextjs",
      "persian",
      "pimx",
      "react",
      "typescript"
    ],
    "updatedAt": "2026-10-07T16:28:23Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxeltex.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:24.345Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_ELTEX/blob/main/README.md",
    "features": [
      "AI episode content, prompts and code resources",
      "Project previews and account features",
      "Comments and administrative content tools"
    ],
    "featuresFa": [
      "محتوای ویدیویی هوش مصنوعی، پرامپت و منابع کد",
      "پیش‌نمایش پروژه و قابلیت‌های حساب کاربری",
      "دیدگاه‌ها و ابزارهای مدیریت محتوا"
    ],
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "github-pimx-weather",
    "repoName": "PIMX_WEATHER",
    "title": "Animated multilingual weather forecasts",
    "titleEn": "Animated multilingual weather forecasts",
    "titleFa": "تجربهٔ بصری آب‌وهوا",
    "description": "A vanilla JavaScript weather dashboard with forecast views, localization, animated styling and astronomical/solar visualizations.",
    "descriptionFa": "وب‌اپ پیش‌بینی آب‌وهوا با زبان‌های مختلف، رابط متحرک و اطلاعات نجومی و خورشیدی در کنار وضعیت جوی.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_WEATHER",
    "accent": "rose",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "JavaScript",
    "technologies": [],
    "topics": [
      "astronomy",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "visualization"
    ],
    "updatedAt": "2026-10-07T16:28:45Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimx-weather.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:19.497Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_WEATHER/blob/main/README.md",
    "linkKind": "website",
    "activitySource": "http",
    "previewImage": "/project-previews/github-pimx-weather.jpg?v=owner-20261008"
  },
  {
    "id": "pimx-pass",
    "repoName": "PIMX_PASS_DNS",
    "title": "Browser-based DNS comparison",
    "titleEn": "Browser-based DNS comparison",
    "titleFa": "مقایسهٔ پاسخ DNS",
    "description": "A bilingual DNS comparison interface with curated resolver sources, browser-based timing tests, result cards and an optional analytics backend.",
    "descriptionFa": "ابزار دوزبانه برای مقایسهٔ پاسخ سرویس‌های DNS منتخب از طریق درخواست‌های مرورگر؛ همراه با توضیحات و تحلیل اختیاری استفاده.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PASS_DNS",
    "accent": "emerald",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "React",
      "Framer Motion"
    ],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "persian",
      "pimx",
      "react",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:28:05Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxpassdns.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:22.533Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PASS_DNS/blob/main/README.md",
    "features": [
      "Curated resolvers and browser request timings",
      "Persian and English interface",
      "Optional usage analytics"
    ],
    "featuresFa": [
      "سرویس‌های DNS منتخب و زمان‌سنجی درخواست‌های مرورگر",
      "رابط فارسی و انگلیسی",
      "تحلیل اختیاری استفاده"
    ],
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "github-pimx-portal",
    "repoName": "PIMX_PORTAL",
    "title": "A gateway to the PIMX ecosystem",
    "titleEn": "A gateway to the PIMX ecosystem",
    "titleFa": "دروازهٔ اکوسیستم PIMX",
    "description": "A bilingual visual directory for the PIMX ecosystem. Distinct project posters lead visitors to individual tools and a support destination.",
    "descriptionFa": "دایرکتوری بصری و دوزبانه برای مرور ابزارها، پروژه‌ها و سرویس‌های اکوسیستم PIMX در یک فضای واحد.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PORTAL",
    "accent": "indigo",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "Express",
      "Framer Motion",
      "React"
    ],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "express",
      "persian",
      "pimx",
      "react",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:27:12Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxportal.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:19.583Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PORTAL/blob/main/README.md",
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "github-pimx-fail",
    "repoName": "PIMX_FAIL",
    "title": "Startup stories and lessons",
    "titleEn": "Startup stories and lessons",
    "titleFa": "آرشیو تجربه‌های استارتاپی",
    "description": "A searchable archive of failed startups with company stories, failure lessons, technical blueprints and an optional Gemini analysis endpoint.",
    "descriptionFa": "آرشیوی از داستان شکست استارتاپ‌ها، درس‌های آموخته‌شده و طرح‌های محصول؛ همراه با قابلیت‌های اختیاری متصل به Gemini.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_FAIL",
    "accent": "violet",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "React",
      "Vite",
      "Express"
    ],
    "topics": [
      "bilingual",
      "case-studies",
      "developer-tools",
      "english",
      "express",
      "persian",
      "pimx",
      "react",
      "startups",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:27:38Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimxfail.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:20.982Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_FAIL/blob/master/README.md",
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "github-pimx",
    "repoName": "PIMX",
    "title": "Portfolio & project ecosystem",
    "titleEn": "Portfolio & project ecosystem",
    "titleFa": "پورتفولیو و اکوسیستم PIMX",
    "description": "The PIMX ecosystem website: a React/TypeScript showcase connecting independent web tools, AI projects and personal engineering work, with a Node server and Pages functions.",
    "descriptionFa": "سایت معرفی پروژه‌ها و مسیر کاری من با React، Vite و Express، آمادهٔ اجرا روی Cloudflare Pages؛ همین پورتفولیو بخشی از این مخزن است.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX",
    "accent": "teal",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "TypeScript",
    "technologies": [
      "React",
      "Vite",
      "Express",
      "Cloudflare Pages"
    ],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "express",
      "persian",
      "pimx",
      "react",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:28:27Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://pimx.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T07:02:04.217Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX/blob/main/README.md",
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "github-import-export-company",
    "repoName": "Import-Export-Company",
    "title": "Import and export company website",
    "titleEn": "Import and export company website",
    "titleFa": "سایت شرکت واردات و صادرات",
    "description": "A multi-page corporate website for an import/export company, implemented with HTML, CSS and JavaScript. The local source folder is `Mr.Amirhosseini`.",
    "descriptionFa": "وب‌سایت شرکتی چندصفحه‌ای با HTML، CSS و JavaScript برای معرفی خدمات واردات و صادرات و راه‌های ارتباطی.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/Import-Export-Company",
    "accent": "teal",
    "category": "featured",
    "badge": "LIVE WEB APP",
    "language": "CSS",
    "technologies": [],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "persian",
      "pimx",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:28:41Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "link": "https://amirhosseini.pages.dev",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T07:02:02.915Z",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/Import-Export-Company/blob/main/README.md",
    "linkKind": "website",
    "activitySource": "http"
  },
  {
    "id": "github-3d-animated-interactive-portfolio",
    "repoName": "3d-animated-interactive-portfolio",
    "title": "Interactive Three.js portfolio",
    "titleEn": "Interactive Three.js portfolio",
    "titleFa": "پورتفولیوی تعاملی سه‌بعدی",
    "description": "A personal portfolio pairing a React Three Fiber frontend with an Express project API. Three.js scenes and Framer Motion transitions frame the project showcase.",
    "descriptionFa": "پورتفولیویی با رابط React Three Fiber و API پروژه‌ها در Express؛ صحنه‌های Three.js و ترنزیشن‌های Framer Motion برای نمایش کارها.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/3d-animated-interactive-portfolio",
    "accent": "gold",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "JavaScript",
    "technologies": [],
    "topics": [
      "astronomy",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "visualization"
    ],
    "updatedAt": "2026-10-07T16:26:53Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/3d-animated-interactive-portfolio/blob/main/README.md"
  },
  {
    "id": "github-bot",
    "repoName": "BOT",
    "title": "Cloudflare-powered Telegram AI assistant",
    "titleEn": "Cloudflare-powered Telegram AI assistant",
    "titleFa": "ربات هوش مصنوعی روی کلادفلر",
    "description": "A Telegram AI assistant implemented as a Cloudflare Worker, with provider routing, chat memory, reminders and per-user timezone helpers.",
    "descriptionFa": "ربات تلگرام روی Cloudflare Workers با مسیریابی میان ارائه‌دهندگان هوش مصنوعی، حافظهٔ گفتگو، یادآوری و مدیریت منطقهٔ زمانی.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/BOT",
    "accent": "violet",
    "category": "ai",
    "badge": "AI WORKSPACE",
    "language": "JavaScript",
    "technologies": [
      "Cloudflare Workers",
      "Telegram"
    ],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "telegram-bot"
    ],
    "updatedAt": "2026-10-07T16:26:57Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/BOT/blob/master/README.md"
  },
  {
    "id": "github-c-mn",
    "repoName": "c-mn",
    "title": "C++ text and file input",
    "titleEn": "C++ text and file input",
    "titleFa": "تمرین فایل و متن در ++C",
    "description": "A C++ console program that reads whitespace-delimited text and writes each value to a file until the user enters exit.",
    "descriptionFa": "تمرین خواندن متن ورودی و ذخیرهٔ آن در فایل تا دریافت دستور خروج؛ تجربه‌ای برای یادگیری ورودی، خروجی و کار با فایل.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/c-mn",
    "accent": "cyan",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "C++",
    "technologies": [],
    "topics": [
      "bilingual",
      "cpp",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises"
    ],
    "updatedAt": "2026-10-07T16:25:19Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/c-mn/blob/main/README.md"
  },
  {
    "id": "github-chat",
    "repoName": "chat",
    "title": "Django chat with persistent conversations",
    "titleEn": "Django chat with persistent conversations",
    "titleFa": "گفتگو با جنگو",
    "description": "A Django chat application with account management, persisted conversations, static assets and an AI response integration.",
    "descriptionFa": "برنامهٔ گفتگو با Django، حساب کاربری، ذخیرهٔ مکالمات و اتصال به هوش مصنوعی؛ تمرینی برای ارتباط رابط وب با منطق سمت سرور.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/chat",
    "accent": "rose",
    "category": "ai",
    "badge": "AI WORKSPACE",
    "language": "HTML",
    "technologies": [
      "Django",
      "AI APIs"
    ],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "python"
    ],
    "updatedAt": "2026-10-07T16:27:23Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/chat/blob/main/README.md"
  },
  {
    "id": "github-chess-timer-with-python",
    "repoName": "chess-timer-with-python",
    "title": "Two-player chess timer",
    "titleEn": "Two-player chess timer",
    "titleFa": "ساعت شطرنج با پایتون",
    "description": "A Tkinter exercise with separate player counters and buttons for switching between players.",
    "descriptionFa": "تایمر دو نفره با Tkinter برای مدیریت نوبت بازیکنان و شمارش زمان؛ ترکیبی از منطق زمان‌بندی و رابط دسکتاپ.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/chess-timer-with-python",
    "accent": "indigo",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:25:24Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/chess-timer-with-python/blob/main/README.md"
  },
  {
    "id": "github-clock",
    "repoName": "clock",
    "title": "A Tkinter digital clock",
    "titleEn": "A Tkinter digital clock",
    "titleFa": "ساعت دیجیتال",
    "description": "A Tkinter digital clock that updates its time label every 200 milliseconds.",
    "descriptionFa": "ساعت گرافیکی Tkinter که هر ۲۰۰ میلی‌ثانیه به‌روز می‌شود؛ تمرینی برای حلقهٔ رویداد و نمایش زندهٔ زمان.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/clock",
    "accent": "teal",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:25:30Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/clock/blob/main/README.md"
  },
  {
    "id": "github-coursera",
    "repoName": "coursera",
    "title": "HTML and CSS course exercises",
    "titleEn": "HTML and CSS course exercises",
    "titleFa": "تمرین‌های طراحی وب",
    "description": "A small collection of HTML/CSS course work with a root page and a module3-solution directory.",
    "descriptionFa": "آرشیو تمرین‌های HTML و CSS دورهٔ Coursera، شامل صفحات اصلی و پاسخ تمرین ماژول سوم.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/coursera",
    "accent": "emerald",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "HTML",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises"
    ],
    "updatedAt": "2026-10-07T16:25:35Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/coursera/blob/main/README.md"
  },
  {
    "id": "github-cpp",
    "repoName": "cpp",
    "title": "C++ matrix exercises",
    "titleEn": "C++ matrix exercises",
    "titleFa": "تمرین ماتریس در ++C",
    "description": "A C++ program that reads a 3×3 integer matrix, separates its columns into arrays and prints column values in sequence.",
    "descriptionFa": "تمرین کار با ماتریس سه‌درسه و ستون‌های آن؛ بخشی از مسیر یادگیری آرایه‌ها و منطق برنامه‌نویسی در ++C.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/cpp",
    "accent": "gold",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "C++",
    "technologies": [],
    "topics": [
      "bilingual",
      "cpp",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises"
    ],
    "updatedAt": "2026-10-07T16:25:42Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/cpp/blob/main/README.md"
  },
  {
    "id": "github-email-generator",
    "repoName": "email-generator",
    "title": "Temporary inbox and message monitoring",
    "titleEn": "Temporary inbox and message monitoring",
    "titleFa": "ابزار ایمیل موقت",
    "description": "A terminal tool for creating temporary inboxes through temp-mail.io, monitoring messages with background threads and extracting likely verification codes.",
    "descriptionFa": "ساخت صندوق‌های ایمیل موقت با temp-mail.io، پایش پیام‌ها در پس‌زمینه و استخراج کدهای دریافتی با پایتون.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/email-generator",
    "accent": "violet",
    "category": "automation",
    "badge": "AUTOMATION",
    "language": "Python",
    "technologies": [],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "python"
    ],
    "updatedAt": "2026-10-07T16:29:15Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/email-generator/blob/main/README.md"
  },
  {
    "id": "github-exam",
    "repoName": "exam",
    "title": "C++ file persistence course exercise",
    "titleEn": "C++ file persistence course exercise",
    "titleFa": "تمرین ورودی و ذخیرهٔ فایل",
    "description": "A forked C++ exercise that experiments with username input and file persistence. It is preserved as a learning snapshot with upstream attribution.",
    "descriptionFa": "فورک یک تمرین درسی ++C برای دریافت نام کاربری و ذخیرهٔ آن در فایل؛ کد و منبع اصلی در گیت‌هاب قابل مشاهده‌اند.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/exam",
    "accent": "cyan",
    "category": "web",
    "badge": "COURSE FORK",
    "language": "C++",
    "technologies": [],
    "topics": [
      "bilingual",
      "cpp",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises"
    ],
    "updatedAt": "2026-10-07T16:25:47Z",
    "isFork": true,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/exam/blob/main/README.md",
    "forkSourceUrl": "https://github.com/Soroush26/exam"
  },
  {
    "id": "github-gussing-number",
    "repoName": "gussing-number",
    "title": "Python number guessing game",
    "titleEn": "Python number guessing game",
    "titleFa": "بازی حدس عدد با پایتون",
    "description": "A console guessing game that chooses a number from 1 to 10 and records the best attempt count during the current session.",
    "descriptionFa": "بازی خط فرمان برای حدس عددی از ۱ تا ۱۰، همراه با شمارش تلاش‌ها و ثبت بهترین نتیجه.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/gussing-number",
    "accent": "rose",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:25:52Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/gussing-number/blob/main/README.md"
  },
  {
    "id": "github-gussing-number-with-js",
    "repoName": "gussing-number-with-js",
    "title": "Browser number guessing game",
    "titleEn": "Browser number guessing game",
    "titleFa": "بازی حدس عدد در مرورگر",
    "description": "A small browser game with a random answer in the range 0–999, higher/lower hints and ten incorrect-guess opportunities.",
    "descriptionFa": "بازی JavaScript با بازهٔ صفر تا ۹۹۹، راهنمای بزرگ‌تر یا کوچک‌تر و محدودیت ده حدس اشتباه.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/gussing-number-with-js",
    "accent": "indigo",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "JavaScript",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises"
    ],
    "updatedAt": "2026-10-07T16:25:57Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/gussing-number-with-js/blob/main/README.md"
  },
  {
    "id": "github-mcino-introduction-to-git-and-github",
    "repoName": "mcino-Introduction-to-Git-and-GitHub",
    "title": "Git and GitHub course exercises",
    "titleEn": "Git and GitHub course exercises",
    "titleFa": "تمرین گیت و گیت‌هاب",
    "description": "A forked Git/GitHub course repository with interest-calculator exercises and upstream community documents.",
    "descriptionFa": "فورک آموزشی دورهٔ آشنایی با Git و GitHub، شامل محاسبهٔ سود با پایتون و مستندات مشارکت در پروژهٔ اصلی.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/mcino-Introduction-to-Git-and-GitHub",
    "accent": "emerald",
    "category": "web",
    "badge": "COURSE FORK",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:26:02Z",
    "isFork": true,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/mcino-Introduction-to-Git-and-GitHub/blob/main/README.md",
    "forkSourceUrl": "https://github.com/ibm-developer-skills-network/mcino-Introduction-to-Git-and-GitHub"
  },
  {
    "id": "mml-wallet-bot",
    "repoName": "mml-wallet",
    "title": "Telegram wallet information workflow",
    "titleEn": "Telegram wallet information workflow",
    "titleFa": "ربات جمع‌آوری اطلاعات کیف پول",
    "description": "A Telegram wallet/collection bot with asynchronous SQLite storage, configurable administrative settings, a keep-alive helper and a Flask database viewer.",
    "descriptionFa": "ربات تلگرام با SQLite، مدیریت اطلاعات کاربران، جریان بررسی توسط ادمین و ابزار Flask برای مشاهدهٔ داده‌ها.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/mml-wallet",
    "accent": "gold",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [
      "SQLite",
      "Telegram",
      "Flask"
    ],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "python",
      "telegram-bot"
    ],
    "updatedAt": "2026-10-07T16:28:56Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/mml-wallet/blob/main/README.md"
  },
  {
    "id": "github-mohammadrezaabedinpoor",
    "repoName": "MOHAMMADREZAABEDINPOOR",
    "title": "My GitHub profile",
    "titleEn": "My GitHub profile",
    "titleFa": "پروفایل توسعه‌دهنده در گیت‌هاب",
    "description": "PIMX · Independent tools, AI workspaces, desktop utilities and 3D experiences · English / فارسی",
    "descriptionFa": "مخزن README پروفایل من در گیت‌هاب؛ معرفی مسیر برنامه‌نویسی، ابزارها و پروژه‌های اکوسیستم PIMX.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/MOHAMMADREZAABEDINPOOR",
    "accent": "violet",
    "category": "web",
    "badge": "GITHUB PROFILE",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "github-profile",
      "persian",
      "pimx",
      "profile-readme"
    ],
    "updatedAt": "2026-10-07T20:26:02Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/MOHAMMADREZAABEDINPOOR/blob/main/README.md"
  },
  {
    "id": "github-my-project",
    "repoName": "my-project",
    "title": "Integer collection and file counting",
    "titleEn": "Integer collection and file counting",
    "titleFa": "تمرین ورودی و خروجی فایل",
    "description": "An early C++ file-I/O exercise that accepts integers until zero, writes nonzero values and prints the input count.",
    "descriptionFa": "برنامهٔ ++C برای دریافت عددها تا ورود صفر، ذخیرهٔ داده‌ها در فایل و شمارش ورودی‌ها.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/my-project",
    "accent": "cyan",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "C++",
    "technologies": [],
    "topics": [
      "bilingual",
      "cpp",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises"
    ],
    "updatedAt": "2026-10-07T16:26:07Z",
    "isFork": false,
    "isArchived": false,
    "stars": 1,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/my-project/blob/main/README.md"
  },
  {
    "id": "github-open-random-window",
    "repoName": "open-random-window",
    "title": "Tkinter window placement experiment",
    "titleEn": "Tkinter window placement experiment",
    "titleFa": "آزمایش پنجره‌های Tkinter",
    "description": "A small Tkinter experiment that creates ten windows with randomized sizes and positions.",
    "descriptionFa": "تمرین رابط گرافیکی پایتون برای ایجاد ده پنجره در موقعیت‌های تصادفی؛ کاوشی در مدیریت پنجره و مختصات.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/open-random-window",
    "accent": "rose",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:26:13Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/open-random-window/blob/main/README.md"
  },
  {
    "id": "personal-resume-gate",
    "repoName": "personal-website",
    "title": "An earlier chapter of my portfolio",
    "titleEn": "An earlier chapter of my portfolio",
    "titleFa": "نسخهٔ پیشین سایت شخصی",
    "description": "A static personal website with project sections, certificate assets, locale data, search-engine metadata and a service worker.",
    "descriptionFa": "پورتفولیوی استاتیک با صفحات معرفی، گواهینامه‌ها، زبان‌های مختلف، تنظیمات SEO و Service Worker؛ بخشی از سیر تکامل سایت من.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/personal-website",
    "accent": "indigo",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "CSS",
    "technologies": [],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "persian",
      "pimx",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:28:36Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/personal-website/blob/main/README.md"
  },
  {
    "id": "pimx-pass-bot",
    "repoName": "PIMX_PASS_BOT",
    "title": "Network configuration discovery tools",
    "titleEn": "Network configuration discovery tools",
    "titleFa": "ربات ابزارهای شبکه",
    "description": "A Telegram bot and companion web interface for finding, parsing and testing network/server configurations. Python modules separate providers, scanning, storage and web serving.",
    "descriptionFa": "ابزار پایتون برای پیدا کردن، پردازش و آزمایش تنظیمات شبکه، جمع‌آوری از منابع مختلف، ذخیرهٔ نتایج و ارائهٔ رابط وب.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PASS_BOT",
    "accent": "teal",
    "category": "automation",
    "badge": "AUTOMATION",
    "language": "Python",
    "technologies": [],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "python",
      "telegram-bot"
    ],
    "updatedAt": "2026-10-07T16:28:50Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PASS_BOT/blob/main/README.md"
  },
  {
    "id": "github-pimx-pass-panel",
    "repoName": "PIMX_PASS_PANEL",
    "title": "Edge-based network management panel",
    "titleEn": "Edge-based network management panel",
    "titleFa": "پنل مدیریت تنظیمات شبکه",
    "description": "A Cloudflare Worker with a Persian management interface, KV-backed state, subscription generation and WebSocket-to-TCP proxy handling.",
    "descriptionFa": "پنل فارسی روی Cloudflare Workers با KV، مدیریت اشتراک‌ها و ارتباط WebSocket به TCP؛ پروژه‌ای برای شناخت معماری سرویس‌های لبه.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PASS_PANEL",
    "accent": "gold",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "JavaScript",
    "technologies": [
      "Cloudflare Workers",
      "KV",
      "WebSocket"
    ],
    "topics": [
      "bilingual",
      "english",
      "networking",
      "persian",
      "pimx",
      "privacy"
    ],
    "updatedAt": "2026-10-07T16:28:10Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PASS_PANEL/blob/main/README.md"
  },
  {
    "id": "github-pimx-personal",
    "repoName": "PIMX_PERSONAL",
    "title": "Network service dashboard",
    "titleEn": "Network service dashboard",
    "titleFa": "داشبورد سرویس‌های شبکه",
    "description": "A React server-discovery dashboard with a Node backend for collecting, testing and listing proxy/server configurations. The source is a network tool despite the repository name.",
    "descriptionFa": "داشبورد React برای نمایش سرورها و پراکسی‌ها، همراه با سرویس Node.js برای جمع‌آوری، آزمایش و فهرست کردن نتایج.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PERSONAL",
    "accent": "violet",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "JavaScript",
    "technologies": [
      "React"
    ],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "persian",
      "pimx",
      "react",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:27:07Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PERSONAL/blob/main/README.md"
  },
  {
    "id": "github-pimx-planner",
    "repoName": "PIMX_PLANNER",
    "title": "Personal and study planning",
    "titleEn": "Personal and study planning",
    "titleFa": "برنامه‌ریز شخصی و تحصیلی",
    "description": "A personal planning workspace with daily tasks, goals, study tracking, grades, reminders, a diary and a chat section. The repository contains React, Node/PostgreSQL, Django and Pages/D1 variants.",
    "descriptionFa": "ابزار برنامه‌ریزی کارها، هدف‌ها، مطالعه، نمره‌ها، یادآوری و یادداشت روزانه؛ با نسخه‌های React، Node، PostgreSQL، Django و Cloudflare D1.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PLANNER",
    "accent": "cyan",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "TypeScript",
    "technologies": [
      "React",
      "PostgreSQL",
      "Django",
      "Cloudflare D1",
      "Express"
    ],
    "topics": [
      "bilingual",
      "developer-tools",
      "english",
      "express",
      "persian",
      "pimx",
      "python",
      "react",
      "typescript",
      "vite",
      "web-app"
    ],
    "updatedAt": "2026-10-07T16:28:17Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PLANNER/blob/main/README.md",
    "features": [
      "Tasks, goals, study planning and grade tracking",
      "Reminders, diary entries and chat interfaces",
      "Multiple backend and deployment experiments"
    ],
    "featuresFa": [
      "کارها، هدف‌ها، برنامهٔ مطالعه و پیگیری نمره‌ها",
      "یادآوری، یادداشت روزانه و رابط گفتگو",
      "تجربهٔ چند معماری بک‌اند و دیپلوی"
    ]
  },
  {
    "id": "pimx-play-bot",
    "repoName": "PIMX_PLAY_BOT",
    "title": "Telegram application discovery",
    "titleEn": "Telegram application discovery",
    "titleFa": "ربات جست‌وجوی اپلیکیشن",
    "description": "A Python Telegram application-discovery bot with provider queries, result matching, interactive keyboards and temporary-file delivery helpers.",
    "descriptionFa": "ربات تلگرام پایتون برای کشف اپلیکیشن، جست‌وجو در ارائه‌دهندگان مختلف، رابط دکمه‌ای و تحویل موقت فایل‌ها.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PLAY_BOT",
    "accent": "rose",
    "category": "automation",
    "badge": "AUTOMATION",
    "language": "Python",
    "technologies": [],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "python",
      "telegram-bot"
    ],
    "updatedAt": "2026-10-07T16:29:01Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_PLAY_BOT/blob/main/README.md"
  },
  {
    "id": "pimx-sonic-bot",
    "repoName": "PIMX_SONIC_BOT",
    "title": "Telegram music and media workflows",
    "titleEn": "Telegram music and media workflows",
    "titleFa": "ربات موسیقی و رسانه",
    "description": "A Python Telegram music/media bot using yt-dlp, asynchronous HTTP, inline controls and local persistence helpers.",
    "descriptionFa": "ربات رسانهٔ تلگرام با yt-dlp، درخواست‌های HTTP ناهمگام، کنترل‌های درون‌خطی و ذخیرهٔ وضعیت.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_SONIC_BOT",
    "accent": "teal",
    "category": "automation",
    "badge": "AUTOMATION",
    "language": "Python",
    "technologies": [
      "yt-dlp",
      "Telegram"
    ],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "python",
      "telegram-bot"
    ],
    "updatedAt": "2026-10-07T16:29:06Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_SONIC_BOT/blob/main/README.md"
  },
  {
    "id": "github-pimx-save-bot",
    "repoName": "PIMX_SAVE_BOT",
    "title": "PIMX_SAVE_BOT",
    "titleEn": "PIMX_SAVE_BOT",
    "titleFa": "ربات ذخیرهٔ رسانه PIMX SAVE",
    "description": "A TypeScript/Deno Telegram media bot on Supabase Edge Functions. It resolves public media links, attempts photo/video/audio delivery, and provides download buttons. Spotify uses track metadata, a YouTube search match, or a preview fallback.",
    "descriptionFa": "ربات رسانهٔ تلگرام با TypeScript و Deno روی Supabase Edge Functions؛ استخراج لینک‌های عمومی، تلاش برای ارسال تصویر، ویدئو یا صوت و ارائهٔ دکمهٔ دانلود. برای Spotify از اطلاعات آهنگ، نتیجهٔ جست‌وجوی YouTube یا پیش‌نمایش استفاده می‌کند.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_SAVE_BOT",
    "accent": "emerald",
    "category": "automation",
    "badge": "ACTIVE TELEGRAM BOT",
    "language": "TypeScript",
    "technologies": [
      "TypeScript",
      "Deno",
      "Supabase Edge Functions",
      "Telegram Bot API",
      "Cobalt",
      "FxTwitter"
    ],
    "topics": [
      "ai-tools",
      "bilingual",
      "deno",
      "english",
      "media-downloader",
      "persian",
      "pimx",
      "supabase",
      "telegram-bot",
      "typescript"
    ],
    "updatedAt": "2026-10-08T12:07:28.585Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/PIMX_SAVE_BOT/blob/main/README.md",
    "features": [
      "Public-link extraction paths for YouTube, Instagram, X, SoundCloud and Spotify",
      "Photo, video and audio delivery with direct-download and source buttons",
      "Spotify track metadata, YouTube search match and preview fallback",
      "Supabase Edge webhook with /start and /help commands"
    ],
    "featuresFa": [
      "مسیرهای استخراج لینک عمومی YouTube، Instagram، X، SoundCloud و Spotify",
      "ارسال تصویر، ویدئو و صوت با دکمهٔ دانلود مستقیم و لینک منبع",
      "اطلاعات آهنگ Spotify، نتیجهٔ جست‌وجوی YouTube و پیش‌نمایش جایگزین",
      "وب‌هوک Supabase Edge با دستورهای /start و /help"
    ],
    "link": "https://t.me/PIMX_SAVE_BOT",
    "linkKind": "bot",
    "activitySource": "owner",
    "liveStatus": "verified",
    "verifiedAt": "2026-10-08T11:56:23.905Z"
  },
  {
    "id": "github-pwa-chatbot",
    "repoName": "pwa-chatbot",
    "title": "Multilingual web chat with Express",
    "titleEn": "Multilingual web chat with Express",
    "titleFa": "وب‌اپ گفتگوی هوشمند",
    "description": "A Node/Express AI-chat project with a companion pimxchat web directory, localized pages and SQLite persistence helpers.",
    "descriptionFa": "برنامهٔ گفتگو با Node.js و Express، صفحات چندزبانه و ذخیرهٔ داده‌ها در SQLite؛ تجربه‌ای برای ساخت یک چت‌بات تحت وب.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/pwa-chatbot",
    "accent": "gold",
    "category": "ai",
    "badge": "AI WORKSPACE",
    "language": "JavaScript",
    "technologies": [
      "Express",
      "SQLite"
    ],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "express",
      "persian",
      "pimx"
    ],
    "updatedAt": "2026-10-07T16:29:10Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/pwa-chatbot/blob/master/README.md"
  },
  {
    "id": "github-shop",
    "repoName": "shop",
    "title": "Avangard — Django online store",
    "titleEn": "Avangard — Django online store",
    "titleFa": "فروشگاه اینترنتی آوانگارد",
    "description": "A Django storefront with catalog search and filtering, product variants, guest and account carts, wishlists, checkout, shipping and order management. The source includes a local payment sandbox and a ZarinPal adapter.",
    "descriptionFa": "فروشگاه Django با جست‌وجو و فیلتر محصولات، تنوع کالا، سبد خرید مهمان و کاربر، علاقه‌مندی‌ها، پرداخت، ارسال و مدیریت سفارش. کد شامل محیط پرداخت آزمایشی و اتصال زرین‌پال است.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/shop",
    "accent": "violet",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [
      "Django"
    ],
    "topics": [
      "bilingual",
      "django",
      "ecommerce",
      "english",
      "persian",
      "pimx",
      "python",
      "shopping-cart"
    ],
    "updatedAt": "2026-10-07T20:25:15Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/shop/blob/main/README.md",
    "features": [
      "Product catalog, filters and variant selection",
      "Guest and account carts, wishlists and addresses",
      "Checkout, shipping and order management",
      "Local payment sandbox and ZarinPal adapter"
    ],
    "featuresFa": [
      "کاتالوگ محصولات، فیلترها و انتخاب تنوع کالا",
      "سبد مهمان و کاربر، علاقه‌مندی‌ها و آدرس‌ها",
      "ثبت سفارش، ارسال و مدیریت سفارش‌ها",
      "پرداخت آزمایشی و اتصال زرین‌پال"
    ],
    "previewImage": "/project-previews/github-shop.jpg?v=owner-20261008"
  },
  {
    "id": "github-shop2",
    "repoName": "shop2",
    "title": "Laravel ecommerce",
    "titleEn": "Laravel ecommerce",
    "titleFa": "فروشگاه با لاراول",
    "description": "A Laravel 13 ecommerce application with an Alpine.js/Tailwind frontend, product variants, customer accounts, carts, orders and role-based administrative workflows.",
    "descriptionFa": "فروشگاه اینترنتی با Laravel 13، Alpine و Tailwind، شامل حساب کاربران، سبد خرید، سفارش‌ها و نقش‌های دسترسی.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/shop2",
    "accent": "cyan",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Blade",
    "technologies": [
      "Laravel",
      "Alpine",
      "Tailwind"
    ],
    "topics": [
      "bilingual",
      "ecommerce",
      "english",
      "laravel",
      "persian",
      "php",
      "pimx",
      "shopping-cart",
      "vite"
    ],
    "updatedAt": "2026-10-07T20:25:21Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/shop2/blob/main/README.md",
    "features": [
      "Laravel accounts, orders and access roles",
      "Alpine and Tailwind interface"
    ],
    "featuresFa": [
      "حساب‌ها، سفارش‌ها و نقش‌های دسترسی در Laravel",
      "رابط Alpine و Tailwind"
    ]
  },
  {
    "id": "github-shop3",
    "previewImage": "/project-previews/github-shop3.jpg",
    "repoName": "shop3",
    "title": "PHP ecommerce with a custom MVC",
    "titleEn": "PHP ecommerce with a custom MVC",
    "titleFa": "فروشگاه با PHP",
    "description": "A framework-free PHP storefront with a small MVC/router layer, SQLite initialization, customer/admin pages and bilingual product content.",
    "descriptionFa": "فروشگاه دوزبانه با PHP، معماری MVC و مسیریاب اختصاصی، SQLite و پنل‌های مشتری و مدیریت.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/shop3",
    "accent": "rose",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "PHP",
    "technologies": [
      "PHP",
      "SQLite",
      "MVC"
    ],
    "topics": [
      "bilingual",
      "ecommerce",
      "english",
      "persian",
      "php",
      "pimx",
      "shopping-cart"
    ],
    "updatedAt": "2026-10-07T20:25:28Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/shop3/blob/main/README.md",
    "features": [
      "Custom PHP MVC and routing architecture",
      "SQLite persistence and bilingual customer/admin views"
    ],
    "featuresFa": [
      "معماری MVC و مسیریابی اختصاصی PHP",
      "ذخیرهٔ SQLite و صفحات دوزبانهٔ مشتری و ادمین"
    ]
  },
  {
    "id": "github-spam-with-pyautogui",
    "repoName": "spam-with-pyautogui",
    "title": "Keyboard event automation exercise",
    "titleEn": "Keyboard event automation exercise",
    "titleFa": "آزمایش اتوماسیون صفحه‌کلید",
    "description": "A short PyAutoGUI experiment that sends a fixed sequence of Windows keyboard events after timed delays.",
    "descriptionFa": "تمرین کوتاه PyAutoGUI برای شناخت رویدادهای صفحه‌کلید و خودکارسازی ورودی؛ یک آزمایش آموزشی پایتون.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/spam-with-pyautogui",
    "accent": "indigo",
    "category": "automation",
    "badge": "AUTOMATION",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:26:17Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/spam-with-pyautogui/blob/main/README.md"
  },
  {
    "id": "github-sqlalchemy",
    "repoName": "sqlalchemy",
    "title": "MySQL and SQLAlchemy CRUD exercises",
    "titleEn": "MySQL and SQLAlchemy CRUD exercises",
    "titleFa": "تمرین‌های پایگاه داده",
    "description": "Four Python ORM exercises demonstrate insertion, selection, update and deletion against a MySQL table.",
    "descriptionFa": "چهار تمرین ORM با SQLAlchemy و MySQL برای ایجاد، خواندن، ویرایش و حذف اطلاعات.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/sqlalchemy",
    "accent": "teal",
    "category": "automation",
    "badge": "AUTOMATION",
    "language": "Python",
    "technologies": [
      "SQLAlchemy",
      "MySQL"
    ],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:26:21Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/sqlalchemy/blob/main/README.md"
  },
  {
    "id": "github-telegram-bot",
    "repoName": "telegram-bot",
    "title": "A Gemini-powered Telegram chatbot",
    "titleEn": "A Gemini-powered Telegram chatbot",
    "titleFa": "ربات گفتگوی Gemini",
    "description": "A compact Telegram long-polling bot that sends user text to the Gemini REST API and applies a system prompt loaded from a local text file.",
    "descriptionFa": "ربات تلگرام با دریافت پیام به روش long polling، اتصال به REST API مدل Gemini و پرامپت سیستمی.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/telegram-bot",
    "accent": "gold",
    "category": "ai",
    "badge": "AI WORKSPACE",
    "language": "Python",
    "technologies": [],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "python",
      "telegram-bot"
    ],
    "updatedAt": "2026-10-07T16:29:30Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/telegram-bot/blob/main/README.md"
  },
  {
    "id": "housing-ads-scrapper-bot",
    "repoName": "telegram-web-scraping-bot",
    "title": "Property discovery assistant",
    "titleEn": "Property discovery assistant",
    "titleFa": "دستیار جست‌وجوی ملک",
    "description": "A collection of Telegram and agent scripts for property-listing discovery, with Agno/Gemini integration and Scrapling extraction helpers.",
    "descriptionFa": "ربات تلگرام برای کشف آگهی‌های ملک با Agno، Gemini و Scrapling؛ اتصال جریان گفتگو به جمع‌آوری اطلاعات وب.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/telegram-web-scraping-bot",
    "accent": "violet",
    "category": "ai",
    "badge": "AI WORKSPACE",
    "language": "Python",
    "technologies": [
      "Agno",
      "Gemini",
      "Scrapling"
    ],
    "topics": [
      "ai-tools",
      "bilingual",
      "english",
      "persian",
      "pimx",
      "python",
      "telegram-bot"
    ],
    "updatedAt": "2026-10-07T16:27:28Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/telegram-web-scraping-bot/blob/master/README.md"
  },
  {
    "id": "github-temperuture",
    "repoName": "temperuture",
    "title": "Temperature control simulation",
    "titleEn": "Temperature control simulation",
    "titleFa": "شبیه‌ساز کنترل دما",
    "description": "A simulated temperature controller with increase/decrease buttons and heater/cooler status labels.",
    "descriptionFa": "رابط پایتون برای شبیه‌سازی کنترل دما، با دکمه‌های گرم‌کننده و خنک‌کننده و نمایش تغییر وضعیت.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/temperuture",
    "accent": "cyan",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:26:26Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/temperuture/blob/main/README.md"
  },
  {
    "id": "github-test",
    "repoName": "test",
    "title": "Interest calculation course exercises",
    "titleEn": "Interest calculation course exercises",
    "titleFa": "تمرین محاسبهٔ سود",
    "description": "A course assignment repository with a shell simple-interest calculator and contribution/community files.",
    "descriptionFa": "مخزن آموزشی شامل محاسبه‌گر سود و مستندات دوره و مشارکت؛ یکی از تجربه‌های اولیهٔ کار با مخزن و خط فرمان.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/test",
    "accent": "rose",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Shell",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises"
    ],
    "updatedAt": "2026-10-07T16:26:30Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/test/blob/main/README.md"
  },
  {
    "id": "github-thermometer",
    "repoName": "thermometer",
    "title": "Reusable graphical thermometer",
    "titleEn": "Reusable graphical thermometer",
    "titleFa": "دماسنج گرافیکی",
    "description": "A reusable Tkinter thermometer class demonstrated with two independent panels.",
    "descriptionFa": "کامپوننت دماسنج قابل استفادهٔ مجدد با Tkinter و دو پنل نمایشی؛ تمرینی برای طراحی عناصر رابط دسکتاپ.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/thermometer",
    "accent": "indigo",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:26:35Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/thermometer/blob/main/README.md"
  },
  {
    "id": "github-time-with-tkinter-library",
    "repoName": "time-with-tkinter-library",
    "title": "Hours, minutes and seconds countdown",
    "titleEn": "Hours, minutes and seconds countdown",
    "titleFa": "شمارش معکوس با Tkinter",
    "description": "A Tkinter countdown exercise with hour, minute and second fields and an expiration dialog.",
    "descriptionFa": "تایمر گرافیکی با ورودی ساعت، دقیقه و ثانیه و پیام پایان زمان؛ کاوشی در زمان‌بندی رویدادهای رابط.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/time-with-tkinter-library",
    "accent": "teal",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:26:39Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/time-with-tkinter-library/blob/main/README.md"
  },
  {
    "id": "github-timer-with-threading-library",
    "repoName": "timer-with-threading-library",
    "title": "Threaded Tkinter counters",
    "titleEn": "Threaded Tkinter counters",
    "titleFa": "تایمرهای چندریسمانی",
    "description": "A Tkinter/threading exercise with two independently started countdown counters.",
    "descriptionFa": "دو شمارنده با Tkinter و threading برای بررسی اجرای هم‌زمان و به‌روزرسانی رابط گرافیکی.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/timer-with-threading-library",
    "accent": "emerald",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:26:44Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/timer-with-threading-library/blob/main/README.md"
  },
  {
    "id": "github-turtle-library",
    "repoName": "turtle-library",
    "title": "Turtle drawing experiments",
    "titleEn": "Turtle drawing experiments",
    "titleFa": "آزمایش‌های Turtle",
    "description": "A collection of introductory Python scripts: one console input exercise and five turtle drawing experiments built from repeated forward/turn commands.",
    "descriptionFa": "تمرین‌های دریافت ورودی و پنج آزمایش رسم با کتابخانهٔ Turtle؛ تجربه‌های ابتدایی هندسه و برنامه‌نویسی تصویری.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/turtle-library",
    "accent": "gold",
    "category": "web",
    "badge": "LEARNING / WEB",
    "language": "Python",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:26:48Z",
    "isFork": false,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/turtle-library/blob/main/README.md"
  },
  {
    "id": "github-web-application-technologies-and-django-coursera",
    "repoName": "Web-Application-Technologies-and-Django-Coursera",
    "title": "Web technologies and Django course archive",
    "titleEn": "Web technologies and Django course archive",
    "titleFa": "تمرین‌های فناوری وب و جنگو",
    "description": "A forked course-material archive organized by Week 1 through Week 5 for Web Application Technologies and Django.",
    "descriptionFa": "فورک آرشیو هفته‌های اول تا پنجم دورهٔ Web Application Technologies and Django؛ نمونه‌های آموزشی با ارجاع به منبع اصلی.",
    "githubUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/Web-Application-Technologies-and-Django-Coursera",
    "accent": "violet",
    "category": "web",
    "badge": "COURSE FORK",
    "language": "HTML",
    "technologies": [],
    "topics": [
      "bilingual",
      "english",
      "learning",
      "persian",
      "pimx",
      "programming-exercises",
      "python"
    ],
    "updatedAt": "2026-10-07T16:25:13Z",
    "isFork": true,
    "isArchived": false,
    "stars": 0,
    "origin": "github",
    "readmeUrl": "https://github.com/MOHAMMADREZAABEDINPOOR/Web-Application-Technologies-and-Django-Coursera/blob/master/README.md",
    "forkSourceUrl": "https://github.com/parthokr/Web-Application-Technologies-and-Django-Coursera"
  }
];
export const githubCatalogStats = { repositories: githubProjects.length, originalRepositories: githubProjects.filter(p => !p.isFork).length, forks: githubProjects.filter(p => p.isFork).length, liveWebsites: githubProjects.filter(p => p.liveStatus === 'verified' && p.linkKind !== 'bot').length, liveBots: githubProjects.filter(p => p.liveStatus === 'verified' && p.linkKind === 'bot').length, languages: new Set(githubProjects.map(p => p.language).filter(Boolean)).size };
