import type { LanguageType } from './translations';
import type { HomeCopy } from './portfolio_home_copy';

// Personal copy uses only details already present in the portfolio and its project catalogue.
type PersonalCopy = Pick<HomeCopy, 'first' | 'second' | 'role' | 'bio' | 'workSub' | 'workDesc' | 'aboutTitle' | 'aboutItalic' | 'aboutBody'>;
export const humanHomeCopy: Record<LanguageType, PersonalCopy> = {
  en: {
    first:'Python. Web.', second:'And AI.',
    role:'I’m Mohammadreza, a developer in Rasht.',
    bio:'I’ve been programming since 2021. I build websites, Telegram bots and AI tools with Python, Django, React and TypeScript. Below are some projects you can try and code you can read.',
    workSub:'Some things I’ve built.',
    workDesc:'An AI workspace, a file converter, satellite tracking and a few other projects. Open the live versions, or look through the source on GitHub.',
    aboutTitle:'Started in 2021.', aboutItalic:'Still learning.',
    aboutBody:'I’m Mohammadreza Abedinpoor, based in Rasht, Iran. I started programming in 2021. My work includes Python and Django, web interfaces with React and TypeScript, Telegram bots and experiments with language models.',
  },
  fa: {
    first:'پایتون. وب.', second:'هوش مصنوعی.',
    role:'من محمدرضام؛ برنامه‌نویس، از رشت.',
    bio:'از ۲۰۲۱ برنامه‌نویسی می‌کنم. با پایتون، جنگو، ری‌اکت و تایپ‌اسکریپت، سایت، ربات تلگرام و ابزار هوش مصنوعی می‌سازم. پایین‌تر چند پروژه هست که می‌توانی امتحانشان کنی و کدشان را بخوانی.',
    workSub:'چند تا از ساخته‌هایم.',
    workDesc:'یک فضای کار با هوش مصنوعی، مبدل فایل، ردیابی ماهواره و چند پروژهٔ دیگر. نسخهٔ آنلاینشان را امتحان کن یا کدشان را در گیت‌هاب ببین.',
    aboutTitle:'از ۲۰۲۱ شروع کردم.', aboutItalic:'هنوز یاد می‌گیرم.',
    aboutBody:'من محمدرضا عابدین‌پورم، از رشت. برنامه‌نویسی را در ۲۰۲۱ شروع کردم. کارهایم شامل پایتون و جنگو، رابط وب با ری‌اکت و تایپ‌اسکریپت، ربات تلگرام و تجربه‌هایی با مدل‌های زبانی است.',
  },
  ar: {
    first:'بايثون. الويب.', second:'والذكاء الاصطناعي.',
    role:'أنا محمد رضا، مطوّر من رشت.',
    bio:'أبرمج منذ 2021. أبني مواقع وروبوتات تلغرام وأدوات ذكاء اصطناعي باستخدام Python وDjango وReact وTypeScript. ستجد أدناه مشاريع يمكنك تجربتها وقراءة شيفرتها.',
    workSub:'بعض ما بنيته.',
    workDesc:'مساحة عمل بالذكاء الاصطناعي، ومحوّل ملفات، وتتبع للأقمار الصناعية، ومشاريع أخرى. جرّب النسخ المباشرة أو اقرأ الشيفرة على GitHub.',
    aboutTitle:'بدأت في 2021.', aboutItalic:'وما زلت أتعلّم.',
    aboutBody:'أنا محمد رضا عابدين بور من رشت في إيران. بدأت البرمجة في 2021. تشمل أعمالي Python وDjango، وواجهات الويب بـReact وTypeScript، وروبوتات تلغرام، وتجارب مع النماذج اللغوية.',
  },
  de: {
    first:'Python. Web.', second:'Und KI.',
    role:'Ich bin Mohammadreza, Entwickler aus Rascht.',
    bio:'Ich programmiere seit 2021. Mit Python, Django, React und TypeScript baue ich Websites, Telegram-Bots und KI-Werkzeuge. Unten findest du Projekte zum Ausprobieren und ihren Quellcode.',
    workSub:'Ein paar meiner Projekte.',
    workDesc:'Ein KI-Arbeitsbereich, ein Dateikonverter, Satellitenverfolgung und weitere Projekte. Probiere die Live-Versionen aus oder sieh dir den Code auf GitHub an.',
    aboutTitle:'Seit 2021 dabei.', aboutItalic:'Ich lerne weiter.',
    aboutBody:'Ich bin Mohammadreza Abedinpoor aus Rascht im Iran. Seit 2021 programmiere ich. Ich arbeite mit Python und Django, entwickle Weboberflächen mit React und TypeScript, baue Telegram-Bots und experimentiere mit Sprachmodellen.',
  },
  fr: {
    first:'Python. Web.', second:'Et IA.',
    role:'Moi, c’est Mohammadreza, développeur à Racht.',
    bio:'Je programme depuis 2021. Je crée des sites, des bots Telegram et des outils d’IA avec Python, Django, React et TypeScript. Voici quelques projets à essayer, avec leur code à consulter.',
    workSub:'Quelques projets que j’ai créés.',
    workDesc:'Un espace de travail avec l’IA, un convertisseur de fichiers, le suivi de satellites et d’autres projets. Essayez les versions en ligne ou consultez le code sur GitHub.',
    aboutTitle:'Depuis 2021.', aboutItalic:'Toujours en apprentissage.',
    aboutBody:'Je suis Mohammadreza Abedinpoor, à Racht en Iran. J’ai commencé à programmer en 2021. Je travaille avec Python et Django, crée des interfaces avec React et TypeScript, des bots Telegram et des expériences avec les modèles de langage.',
  },
  it: {
    first:'Python. Web.', second:'E IA.',
    role:'Sono Mohammadreza, sviluppatore a Rasht.',
    bio:'Programmo dal 2021. Creo siti, bot Telegram e strumenti di IA con Python, Django, React e TypeScript. Qui sotto trovi alcuni progetti da provare e il loro codice da leggere.',
    workSub:'Qualche progetto che ho creato.',
    workDesc:'Uno spazio di lavoro con IA, un convertitore di file, il tracciamento dei satelliti e altri progetti. Prova le versioni online o guarda il codice su GitHub.',
    aboutTitle:'Ho iniziato nel 2021.', aboutItalic:'Continuo a imparare.',
    aboutBody:'Sono Mohammadreza Abedinpoor e vivo a Rasht, in Iran. Ho iniziato a programmare nel 2021. Lavoro con Python e Django, creo interfacce con React e TypeScript, bot Telegram ed esperimenti con i modelli linguistici.',
  },
  zh: {
    first:'Python。网页。', second:'还有 AI。',
    role:'我是 Mohammadreza，一名在拉什特的开发者。',
    bio:'我从 2021 年开始编程，使用 Python、Django、React 和 TypeScript 开发网站、Telegram 机器人和 AI 工具。下面这些项目可以直接试用，也可以查看源代码。',
    workSub:'我做过的一些项目。',
    workDesc:'AI 工作空间、文件转换工具、卫星追踪，还有其他项目。可以试用在线版本，或在 GitHub 上查看代码。',
    aboutTitle:'从 2021 年开始。', aboutItalic:'还在不断学习。',
    aboutBody:'我是 Mohammadreza Abedinpoor，生活在伊朗拉什特。我从 2021 年开始编程，使用 Python 和 Django，也用 React 和 TypeScript 开发网页界面，制作 Telegram 机器人，并尝试将语言模型用在项目中。',
  },
  ru: {
    first:'Python. Веб.', second:'И ИИ.',
    role:'Я Мохаммадреза, разработчик из Решта.',
    bio:'Я программирую с 2021 года. Делаю сайты, Telegram-ботов и инструменты с ИИ на Python, Django, React и TypeScript. Ниже — проекты, которые можно попробовать, и их исходный код.',
    workSub:'Несколько моих проектов.',
    workDesc:'Рабочее пространство с ИИ, конвертер файлов, отслеживание спутников и другие проекты. Попробуйте работающие версии или посмотрите код на GitHub.',
    aboutTitle:'Начал в 2021 году.', aboutItalic:'Продолжаю учиться.',
    aboutBody:'Я Мохаммадреза Абединпур из Решта, Иран. Начал программировать в 2021 году. Работаю с Python и Django, создаю веб-интерфейсы на React и TypeScript, Telegram-ботов и экспериментирую с языковыми моделями.',
  },
  el: {
    first:'Python. Ιστός.', second:'Και AI.',
    role:'Είμαι ο Mohammadreza, προγραμματιστής από το Ραστ.',
    bio:'Προγραμματίζω από το 2021. Φτιάχνω ιστοσελίδες, bots Telegram και εργαλεία AI με Python, Django, React και TypeScript. Παρακάτω θα βρεις έργα για να δοκιμάσεις και τον κώδικά τους.',
    workSub:'Μερικά έργα που έφτιαξα.',
    workDesc:'Ένας χώρος εργασίας με AI, ένας μετατροπέας αρχείων, παρακολούθηση δορυφόρων και άλλα έργα. Δοκίμασε τις ζωντανές εκδόσεις ή δες τον κώδικα στο GitHub.',
    aboutTitle:'Ξεκίνησα το 2021.', aboutItalic:'Συνεχίζω να μαθαίνω.',
    aboutBody:'Είμαι ο Mohammadreza Abedinpoor από το Ραστ του Ιράν. Ξεκίνησα τον προγραμματισμό το 2021. Δουλεύω με Python και Django, δημιουργώ διεπαφές με React και TypeScript, bots Telegram και πειραματίζομαι με γλωσσικά μοντέλα.',
  },
  la: {
    first:'Python. Tela.', second:'Et AI.',
    role:'Mohammadreza sum, programmator Rashtensis.',
    bio:'Ab anno 2021 programmata scribo. Situs interretiales, automata Telegram et instrumenta intellegentiae artificialis facio, Python, Django, React et TypeScript adhibens. Infra opera experiri et codicem legere potes.',
    workSub:'Nonnulla opera mea.',
    workDesc:'Spatium laboris cum AI, instrumentum ad formas tabularum mutandas, investigatio satellitum et alia opera. Versiones in interrete experire vel codicem in GitHub lege.',
    aboutTitle:'Anno 2021 coepi.', aboutItalic:'Adhuc disco.',
    aboutBody:'Mohammadreza Abedinpoor sum, Rasht in Irania habito. Anno 2021 programmata scribere coepi. Python et Django adhibeo, interfaces cum React et TypeScript et automata Telegram facio, atque exempla linguistica experior.',
  },
};

export const humanFooterCopy: Record<LanguageType, { intro: string; first: string; second: string; note: string }> = {
  en:{intro:'Want to work together?',first:'Tell me about',second:'your project.',note:'Mohammadreza / Rasht, Iran'},
  fa:{intro:'می‌خواهی با هم کار کنیم؟',first:'از پروژه‌ات',second:'برام بگو.',note:'محمدرضا / رشت، ایران'},
  ar:{intro:'هل نعمل معًا؟',first:'حدّثني عن',second:'مشروعك.',note:'محمد رضا / رشت، إيران'},
  de:{intro:'Zusammenarbeiten?',first:'Erzähl mir von',second:'deinem Projekt.',note:'Mohammadreza / Rascht, Iran'},
  fr:{intro:'On travaille ensemble ?',first:'Parlez-moi de',second:'votre projet.',note:'Mohammadreza / Racht, Iran'},
  it:{intro:'Lavoriamo insieme?',first:'Parlami del',second:'tuo progetto.',note:'Mohammadreza / Rasht, Iran'},
  zh:{intro:'一起做个项目？',first:'聊聊你的',second:'项目吧。',note:'Mohammadreza / 伊朗拉什特'},
  ru:{intro:'Поработаем вместе?',first:'Расскажите о',second:'своём проекте.',note:'Мохаммадреза / Решт, Иран'},
  el:{intro:'Να συνεργαστούμε;',first:'Πες μου για',second:'το έργο σου.',note:'Mohammadreza / Ραστ, Ιράν'},
  la:{intro:'Una laboremus?',first:'De opere tuo',second:'mihi narra.',note:'Mohammadreza / Rasht, Irania'},
};
